title: "Cadmus NDP Help"
description: "Help documentation for Cadmus Naples Dante Project"
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version: "11.4.1"

enable_copy_code_button: true

nav_sort: case_insensitive
