title: "Cadmus NDP Help"
description: "Help documentation for Cadmus Naples Dante Project"

remote_theme: just-the-docs/just-the-docs

url: "https://fedhlab.github.io/cadmus-ndp-help"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version: "11.4.1"

enable_copy_code_button: true
nav_sort: case_insensitive
